---
title: "COVID-19 state Reopenings"
output: github_document
---

The ultimate goal here it to see if there's a noticeable impact on COVID-19 cases as different states start to reopen.  

```{r, include=FALSE}
# Load libraries
library(tidyverse)
library(lubridate)
library(data.table) # need this for the "%like%"function
library(wesanderson)
library(scales)
```

```{r}
# Load John Hopkins case data
jhu_latest_raw <- read.csv("https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_confirmed_US.csv")

```

```{r, warning=FALSE}
# do some data cleaning
jhu_latest <- jhu_latest_raw 
jhu_latest <- jhu_latest %>% filter(iso3 == "USA") %>%
 select(-UID, -iso2, -iso3, -code3, -FIPS, -Admin2, -Country_Region, -Lat, -Long_, -Combined_Key) 

by_state <- jhu_latest %>% 
  group_by(Province_State) %>%
  summarise_all(funs(sum(.))) %>%
  column_to_rownames(var = "Province_State") %>%
  t() %>%
  as.data.frame() %>%
  rownames_to_column() %>%
  mutate(date = str_sub(rowname, 2)) %>%
  select(date, everything()) %>%
  select(-rowname) %>%
  mutate(date = mdy(date))
```

The blue line is the date FL started to reopen
```{r}
# plot select states (initially selecting some of the states where people are protesting, will refine with more precise selection)
states = c("Florida", "Georgia", "Michigan", "California", "Illinois", "Pennsylvania")
states <- by_state %>%
  select(date, all_of(states)) %>%
  gather(key = "State", value = "value", -date)


ggplot(states, aes(x = date, y = value)) + 
  geom_line(stat= "identity", aes(color = State)) + 
  scale_x_date(date_breaks = "1 week") +
  ylab("Number of Cases") + 
  scale_y_continuous(labels = comma) +
  geom_vline(xintercept = as.Date("2020-05-04"), linetype="dotted", 
                color = "blue", size=1.5) +
  theme_minimal() + 
  theme(axis.text.x=element_text(angle=60, hjust=1))

```
Y-axis on a logarithmic scale
```{r, warning=FALSE}

ggplot(states, aes(x = date, y = value)) + 
  geom_line(aes(color = State)) + 
  scale_x_date(date_breaks = "1 weeks") +
  ylab("Number of Cases (logarithmic axis") + 
  xlab("Week") +
  scale_y_continuous(trans = "log2") +
  geom_vline(xintercept = as.Date("2020-05-04"), linetype="dotted", 
                color = "blue", size=1.5) +
  theme_minimal() + 
  theme(axis.text.x=element_text(angle=60, hjust=1)) 
```

Last Updated:
```{r echo=FALSE}
Sys.time()
```


To Do:
* Refresh States